export const dataSources = [
  {
    id: 1,
    name: '20 Newsgroups',
    modality: 'Text',
    provider: 'Public',
    dataAvailability: 'Jason Rennie',
    personalData: 'Anonymized',
    terms: 'CC0-1.1',
    homepage: 'Link',
  },
  {
    id: 2,
    name: '2018 Data Science',
    modality: 'Images',
    provider: 'Geated',
    dataAvailability: 'Jason Rennie',
    personalData: 'No Personal Data',
    terms: 'CC0-1.3',
    homepage: 'Link',
  },
  {
    id: 3,
    name: '20 Newsgroups',
    modality: 'Video',
    provider: 'Public',
    dataAvailability: 'Jason Rennie',
    personalData: 'Personally identifiable',
    terms: 'CC0-1.1',
    homepage: 'Link',
  },
  {
    id: 4,
    name: '2010 i2b2/VA',
    modality: 'Tabular',
    provider: 'Geated',
    dataAvailability: 'Jason Rennie',
    personalData: 'Anonymized',
    terms: 'CC0-1.4',
    homepage: 'Link',
  },
  {
    id: 5,
    name: '2018 Data Science',
    modality: 'Audio',
    provider: 'Public',
    dataAvailability: 'Jason Rennie',
    personalData: 'No Personal Data',
    terms: 'CC0-1.0',
    homepage: 'Link',
  },
  {
    id: 6,
    name: '20 Newsgroups',
    modality: 'Text',
    provider: 'Geated',
    dataAvailability: 'Jason Rennie',
    personalData: 'Anonymized',
    terms: 'CC0-1.1',
    homepage: 'Link',
  },
  {
    id: 7,
    name: '2018 Data Science',
    modality: 'Images',
    provider: 'Public',
    dataAvailability: 'Jason Rennie',
    personalData: 'No Personal Data',
    terms: 'CC0-1.3',
    homepage: 'Link',
  },
  {
    id: 8,
    name: '20 Newsgroups',
    modality: 'Video',
    provider: 'Public',
    dataAvailability: 'Jason Rennie',
    personalData: 'Personally identifiable',
    terms: 'CC0-1.1',
    homepage: 'Link',
  },
  {
    id: 9,
    name: '20 Newsgroups',
    modality: 'Text',
    provider: 'Public',
    dataAvailability: 'Jason Rennie',
    personalData: 'Anonymized',
    terms: 'CC0-1.1',
    homepage: 'Link',
  },
  {
    id: 10,
    name: '2018 Data Science',
    modality: 'Images',
    provider: 'Geated',
    dataAvailability: 'Jason Rennie',
    personalData: 'No Personal Data',
    terms: 'CC0-1.3',
    homepage: 'Link',
  },
  {
    id: 11,
    name: '20 Newsgroups',
    modality: 'Video',
    provider: 'Public',
    dataAvailability: 'Jason Rennie',
    personalData: 'Personally identifiable',
    terms: 'CC0-1.1',
    homepage: 'Link',
  },
  {
    id: 12,
    name: '2010 i2b2/VA',
    modality: 'Tabular',
    provider: 'Geated',
    dataAvailability: 'Jason Rennie',
    personalData: 'Anonymized',
    terms: 'CC0-1.4',
    homepage: 'Link',
  },
  {
    id: 13,
    name: '2018 Data Science',
    modality: 'Audio',
    provider: 'Public',
    dataAvailability: 'Jason Rennie',
    personalData: 'No Personal Data',
    terms: 'CC0-1.0',
    homepage: 'Link',
  },
  {
    id: 14,
    name: '20 Newsgroups',
    modality: 'Text',
    provider: 'Geated',
    dataAvailability: 'Jason Rennie',
    personalData: 'Anonymized',
    terms: 'CC0-1.1',
    homepage: 'Link',
  },
  {
    id: 15,
    name: '2018 Data Science',
    modality: 'Images',
    provider: 'Public',
    dataAvailability: 'Jason Rennie',
    personalData: 'No Personal Data',
    terms: 'CC0-1.3',
    homepage: 'Link',
  },
  {
    id: 16,
    name: '20 Newsgroups',
    modality: 'Video',
    provider: 'Public',
    dataAvailability: 'Jason Rennie',
    personalData: 'Personally identifiable',
    terms: 'CC0-1.1',
    homepage: 'Link',
  },
  {
    id: 17,
    name: '20 Newsgroups',
    modality: 'Text',
    provider: 'Public',
    dataAvailability: 'Jason Rennie',
    personalData: 'Anonymized',
    terms: 'CC0-1.1',
    homepage: 'Link',
  },
  {
    id: 18,
    name: '2018 Data Science',
    modality: 'Images',
    provider: 'Geated',
    dataAvailability: 'Jason Rennie',
    personalData: 'No Personal Data',
    terms: 'CC0-1.3',
    homepage: 'Link',
  },
  {
    id: 19,
    name: '20 Newsgroups',
    modality: 'Video',
    provider: 'Public',
    dataAvailability: 'Jason Rennie',
    personalData: 'Personally identifiable',
    terms: 'CC0-1.1',
    homepage: 'Link',
  },
  {
    id: 20,
    name: '2010 i2b2/VA',
    modality: 'Tabular',
    provider: 'Geated',
    dataAvailability: 'Jason Rennie',
    personalData: 'Anonymized',
    terms: 'CC0-1.4',
    homepage: 'Link',
  },
  {
    id: 21,
    name: '2018 Data Science',
    modality: 'Audio',
    provider: 'Public',
    dataAvailability: 'Jason Rennie',
    personalData: 'No Personal Data',
    terms: 'CC0-1.0',
    homepage: 'Link',
  },
  {
    id: 22,
    name: '20 Newsgroups',
    modality: 'Text',
    provider: 'Geated',
    dataAvailability: 'Jason Rennie',
    personalData: 'Anonymized',
    terms: 'CC0-1.1',
    homepage: 'Link',
  },
  {
    id: 23,
    name: '2018 Data Science',
    modality: 'Images',
    provider: 'Public',
    dataAvailability: 'Jason Rennie',
    personalData: 'No Personal Data',
    terms: 'CC0-1.3',
    homepage: 'Link',
  },
  {
    id: 24,
    name: '20 Newsgroups',
    modality: 'Video',
    provider: 'Public',
    dataAvailability: 'Jason Rennie',
    personalData: 'Personally identifiable',
    terms: 'CC0-1.1',
    homepage: 'Link',
  },
  {
    id: 25,
    name: '2018 Data Science',
    modality: 'Images',
    provider: 'Geated',
    dataAvailability: 'Jason Rennie',
    personalData: 'No Personal Data',
    terms: 'CC0-1.3',
    homepage: 'Link',
  },
  {
    id: 26,
    name: '20 Newsgroups',
    modality: 'Video',
    provider: 'Public',
    dataAvailability: 'Jason Rennie',
    personalData: 'Personally identifiable',
    terms: 'CC0-1.1',
    homepage: 'Link',
  },
  {
    id: 27,
    name: '2010 i2b2/VA',
    modality: 'Tabular',
    provider: 'Geated',
    dataAvailability: 'Jason Rennie',
    personalData: 'Anonymized',
    terms: 'CC0-1.4',
    homepage: 'Link',
  },
  {
    id: 28,
    name: '2018 Data Science',
    modality: 'Audio',
    provider: 'Public',
    dataAvailability: 'Jason Rennie',
    personalData: 'No Personal Data',
    terms: 'CC0-1.0',
    homepage: 'Link',
  },
  {
    id: 29,
    name: '20 Newsgroups',
    modality: 'Text',
    provider: 'Geated',
    dataAvailability: 'Jason Rennie',
    personalData: 'Anonymized',
    terms: 'CC0-1.1',
    homepage: 'Link',
  },
  {
    id: 30,
    name: '2018 Data Science',
    modality: 'Images',
    provider: 'Public',
    dataAvailability: 'Jason Rennie',
    personalData: 'No Personal Data',
    terms: 'CC0-1.3',
    homepage: 'Link',
  },
];
